name: Lint Code Base

on:
  merge:
    branches: [dev]

jobs:
  build:
    name: Lint Code Base
    runs-on: unbutu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}